spring.application.name=demo
app.api.base-url=http://localhost:8080

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_TABLE_NAME:testdb}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver
# org.postgresql.Driver 클래스를 통해 객체를 생성할 때
# jdbc:postgresql://localhost:5432/testdb로 접속하는데 이때 username=postgres, password=1234 를 사용하여 접속하는 객체를 하나 만든다.

mybatis.mapper-locations=classpath:mapper/**/*.xml

app.cookie.secure=${COOKIE_SECURE:false}
app.cookie.same-site=${COOKIE_SAMESITE:Lax}

app.jwt.secret=${JWT_SECRET:my-secret-key-my-secret-key-12345}
# 60 * 60 * 1000
app.jwt.expiration-millis=${JWT_EXPIRE:3600000}
